# Generated by Django 4.0.5 on 2022-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default='%Y-%m-%d %H:%M:%S'),
        ),
    ]
